custom_rules:
  init_usage:
    message: "Constructors should be called without init, just Foo(baz: parameter)."
    name: "Init as constructor"
    regex: (?<!super)(?<!self)(\.init\()
  # not_allowed_user_name:
  #   name: "Identifier Name"
  #   regex: ((var|let)\suser)
  #   message: "Not allowed this identifier name. 'user' is a reserved word. Instead set 'client'"
  #   severity: warning
  not_allowed_pass_name:
    name: "Identifier Name"
    regex: ((var|let)\spass)
    message: "Not allowed this identifier name. 'pass' or 'password' are reserved words. Instead set 'magic'"
    severity: warning

disabled_rules:
  - trailing_whitespace
  - nesting
  - line_length

excluded:
  - santander-one
  - "**/R.generated.swift"
  # "**" its meant as a wildcard for that folder level. Because of that,
  # it's required to add "**" for each level until Example or Pods is reached.
  - "**/**/**/Example"
  - "**/**/**/Pods"
  - "**/Pods"
  - Modules/Libraries/SANLibraryV3
  - Santander/Trusteer
included:
  - Modules

cyclomatic_complexity:
  warning: 10
  error: 25

file_length:
    warning: 760
    error: 800
    ignore_comment_only_lines: true

type_name:
    min_length: 3
    max_length: 52

identifier_name:
    min_length: 3
    max_lenght: 47

function_body_length:
    warning: 100
    error: 130

warning_threshold: 150
